version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/etc/php/7.4/fpm/conf.d/custom.ini
    links:
      - database
    networks:
      - default

  node:
    image: digitallyseamless/nodejs-bower-grunt
    working_dir: /var/www
    volumes:
      - ./:/var/www

  database:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/docker.cnf
    environment:
      MYSQL_ROOT_PASSWORD: useladame
      MYSQL_DATABASE: useladame
      MYSQL_USER: useladame
      MYSQL_PASSWORD: useladame
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/sites-available/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    links:
      - php
